spring:
  redis:
    host: 10.40.0.190 # host ,默认 localhost
    port: 6379 # 端口号，默认6379
    pool:
      # 设置都是默认值，可以按需求设计
      max-active: 8 # 可用连接实例的最大数目，默认值为8；如果赋值为-1，则表示不限制；
      max-idle: 8  # 控制一个pool最多有多少个状态为idle(空闲的)的redis实例，默认值也是8。
      max-wait: -1 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。
      min-idle: 0 # 控制一个pool最少有多少个状态为idle(空闲的)的redis实例，默认值为0。
    timeout: 0 # 连接超时时间 单位 ms，默认为0
    password: master # 密码，根据自己的 redis 设计，默认为空